<a href="https://colab.research.google.com/github/JozefSL/pyNotes/blob/main/NorthDakota/ffDataND.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
import zipfile
import io
import datetime

# **Download zipFiles from FracFocus.org**

In [3]:
link2FFcsvZip = 'http://fracfocusdata.org/digitaldownload/FracFocusCSV.zip'

In [4]:
request = requests.get(link2FFcsvZip)
zipBag = zipfile.ZipFile(io.BytesIO(request.content))

In [5]:
zipFiles = zipBag.namelist()
zipFiles

['FracFocusRegistry_1.csv',
 'FracFocusRegistry_10.csv',
 'FracFocusRegistry_11.csv',
 'FracFocusRegistry_12.csv',
 'FracFocusRegistry_13.csv',
 'FracFocusRegistry_14.csv',
 'FracFocusRegistry_15.csv',
 'FracFocusRegistry_16.csv',
 'FracFocusRegistry_17.csv',
 'FracFocusRegistry_18.csv',
 'FracFocusRegistry_19.csv',
 'FracFocusRegistry_2.csv',
 'FracFocusRegistry_20.csv',
 'FracFocusRegistry_21.csv',
 'FracFocusRegistry_22.csv',
 'FracFocusRegistry_23.csv',
 'FracFocusRegistry_24.csv',
 'FracFocusRegistry_25.csv',
 'FracFocusRegistry_3.csv',
 'FracFocusRegistry_4.csv',
 'FracFocusRegistry_5.csv',
 'FracFocusRegistry_6.csv',
 'FracFocusRegistry_7.csv',
 'FracFocusRegistry_8.csv',
 'FracFocusRegistry_9.csv',
 'readme.txt',
 'registryupload_1.csv',
 'registryupload_2.csv',
 'registryupload_3.csv']

# **Unzip the files and create the corresponding dataframes**

In [6]:
RegistryUpload_files=[]
FracFocusRegistry_files=[]

In [7]:
for file_name in zipFiles:
    if (('registryupload' in file_name)) & (file_name.endswith('.csv')):
        RegistryUpload_files.append(file_name)
    if (('FracFocusRegistry' in file_name)) & (file_name.endswith('.csv')):
        FracFocusRegistry_files.append(file_name)

In [9]:
RegistryUpload_files

['registryupload_1.csv', 'registryupload_2.csv', 'registryupload_3.csv']

In [11]:
dfs = list()
for file_name in RegistryUpload_files:
    df = pd.read_csv(zipBag.open(file_name), low_memory=False, dtype={'APINumber': 'str','StateNumber': 'str', 'CountyNumber': 'str'})
    dfs.append(df)

RegistryUpload = pd.concat(dfs, axis=0, ignore_index=True)
RegistryUpload.head(2)

,pKey,JobStartDate,JobEndDate,APINumber,StateNumber,CountyNumber,OperatorName,WellName,Latitude,Longitude,...,TVD,TotalBaseWaterVolume,TotalBaseNonWaterVolume,StateName,CountyName,FFVersion,FederalWell,IndianWell,Source,DTMOD
0,448c1dab-c7fd-4e07-9d6f-e3b1cf64b708,5/1/1955 12:00:00 AM,5/1/1955 12:00:00 AM,42317372620000,42,317,Pioneer Natural Resources,Rogers 42 #5,32.283431,-101.906575,...,NaN,NaN,NaN,Texas,Martin,1,False,False,NaN,NaN
1,f66add2e-8ea8-4843-9388-24725b5d37c1,5/19/1982 12:00:00 AM,5/19/1982 12:00:00 AM,49009219470000,49,009,"Chesapeake Operating, Inc.",WILLIAM VALENTINE 1,42.972810,-105.953840,...,NaN,NaN,NaN,WYOMING,CONVERSE,1,False,False,NaN,NaN

In [8]:
FracFocusRegistry_files

['FracFocusRegistry_1.csv',
 'FracFocusRegistry_10.csv',
 'FracFocusRegistry_11.csv',
 'FracFocusRegistry_12.csv',
 'FracFocusRegistry_13.csv',
 'FracFocusRegistry_14.csv',
 'FracFocusRegistry_15.csv',
 'FracFocusRegistry_16.csv',
 'FracFocusRegistry_17.csv',
 'FracFocusRegistry_18.csv',
 'FracFocusRegistry_19.csv',
 'FracFocusRegistry_2.csv',
 'FracFocusRegistry_20.csv',
 'FracFocusRegistry_21.csv',
 'FracFocusRegistry_22.csv',
 'FracFocusRegistry_23.csv',
 'FracFocusRegistry_24.csv',
 'FracFocusRegistry_25.csv',
 'FracFocusRegistry_3.csv',
 'FracFocusRegistry_4.csv',
 'FracFocusRegistry_5.csv',
 'FracFocusRegistry_6.csv',
 'FracFocusRegistry_7.csv',
 'FracFocusRegistry_8.csv',
 'FracFocusRegistry_9.csv']

In [10]:
dfs = list()
for file_name in FracFocusRegistry_files:
    df = pd.read_csv(zipBag.open(file_name), low_memory=False, dtype={'APINumber': 'str','StateNumber': 'str', 'CountyNumber': 'str'})
    dfs.append(df)

FracFocusRegistry = pd.concat(dfs, axis=0, ignore_index=True)
FracFocusRegistry.head(2)

,UploadKey,JobStartDate,JobEndDate,APINumber,StateNumber,CountyNumber,OperatorName,WellName,Latitude,Longitude,...,IngredientKey,IngredientName,CASNumber,PercentHighAdditive,PercentHFJob,IngredientComment,IngredientMSDS,MassIngredient,ClaimantCompany,DisclosureKey
0,448c1dab-c7fd-4e07-9d6f-e3b1cf64b708,5/1/1955 12:00:00 AM,5/1/1955 12:00:00 AM,42317372620000,42,317,Pioneer Natural Resources,Rogers 42 #5,32.283431,-101.906575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,448c1dab-c7fd-4e07-9d6f-e3b1cf64b708,5/1/1955 12:00:00 AM,5/1/1955 12:00:00 AM,42317372620000,42,317,Pioneer Natural Resources,Rogers 42 #5,32.283431,-101.906575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
FracFocusRegistry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6058540 entries, 0 to 6058539
Data columns (total 39 columns):
 #   Column                   Dtype
---  ------                   -----
 0   UploadKey                object
 1   JobStartDate             object
 2   JobEndDate               object
 3   APINumber                object
 4   StateNumber              object
 5   CountyNumber             object
 6   OperatorName             object
 7   WellName                 object
 8   Latitude                 float64
 9   Longitude                float64
 10  Projection               object
 11  TVD                      float64
 12  TotalBaseWaterVolume     float64
 13  TotalBaseNonWaterVolume  float64
 14  StateName                object
 15  CountyName               object
 16  FFVersion                int64
 17  FederalWell              bool
 18  IndianWell               bool
 19  Source                   float64
 20  DTMOD                    float64
 21  PurposeKey               object
 22  TradeName                object
 23  Supplier                 object
 24  Purpose                  object
 25  SystemApproach           float64
 26  IsWater                  float64
 27  PurposePercentHFJob      float64
 28  PurposeIngredientMSDS    float64
 29  IngredientKey            object
 30  IngredientName           object
 31  CASNumber                object
 32  PercentHighAdditive      float64
 33  PercentHFJob             float64
 34  IngredientComment        object
 35  IngredientMSDS           object
 36  MassIngredient           float64
 37  ClaimantCompany          object
 38  DisclosureKey            object
dtypes: bool(2), float64(14), int64(1), object(22)
memory usage: 1.7+ GB

# **Filter out ND wells and extract water volume used during completions**

In [284]:
ffWellsND = RegistryUpload[['pKey','APINumber','JobEndDate','TotalBaseWaterVolume']][RegistryUpload['StateNumber']== '33'].reset_index(drop=True)

In [285]:
ffWellsND['JobEndDate'] = pd.to_datetime(ffWellsND['JobEndDate'], errors = 'coerce').dt.date

In [286]:
ffWellsND.tail()

,pKey,APINumber,JobEndDate,TotalBaseWaterVolume
16088,7bcd8e47-5d52-412f-a6d1-541b9c7d0176,33025041590000,2023-08-12,5686172.0
16089,5bdc190d-f254-4d47-be29-d51c675a4c8f,33025034420000,2023-08-12,5680525.0
16090,3c2015ec-5a6c-4391-8b6e-09716078f492,33025034470000,2023-08-13,6166909.0
16091,e87c2b7b-4d6d-4ff5-b953-f2a738b31b1d,33025046910000,2023-08-13,7494120.0
16092,c854e631-771b-4373-bdf8-badddaf62c2b,33025046920000,2023-08-13,7266037.0

# **Estimate proppant used during completions in ND**

In [258]:
swData = FracFocusRegistry[['UploadKey','APINumber','JobEndDate','IngredientName','Purpose','TradeName','MassIngredient','PercentHFJob','IngredientKey','TotalBaseWaterVolume']][FracFocusRegistry['StateNumber']== '33'].reset_index(drop=True)
swData['JobEndDate'] = pd.to_datetime(swData['JobEndDate'], errors = 'coerce').dt.date

In [259]:
#swData[swData['MassIngredient']==0].tail(6)

In [260]:
tnWords = ['sand','mesh','proppant','ceramic','quartz','silica','crystalline']

In [261]:
#swDataFilter = swData[swData['Purpose'].str.contains('|'.join(tnWords), case=False, na=False, regex = True)].copy().reset_index(drop=True)
swDataFilter = swData[swData['TradeName'].str.contains('|'.join(tnWords), case=False, na=False, regex = True)].copy().reset_index(drop=True)
#swDataFilter = swData[swData['IngredientName'].str.contains('|'.join(tnWords), case=False, na=False, regex = True)].copy().reset_index(drop=True)
swDataFilter.tail(2)

,UploadKey,APINumber,JobEndDate,IngredientName,Purpose,TradeName,MassIngredient,PercentHFJob,IngredientKey,TotalBaseWaterVolume
44518,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - PREMIUM WHITE,7363600.0,13.596038,ad1a2155-6dfd-40a9-96e1-189eb344478e,5377176.0
44519,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - COMMON WHITE,1805900.0,3.334386,93c1b66d-f3f6-45a0-b17d-9aa939f357df,5377176.0

In [262]:
exclusionList = ['water','transport','acid','stabilizer','carrier','clay','ammonium','chloride','Potassium','KCL','chlorine','naphtha','petroleum','aromatic','surfactant','alcohol','gum','tetrahydrate','carbonate','glycol']

In [263]:
swDataFilter = swDataFilter[~swDataFilter['TradeName'].str.contains('|'.join(exclusionList), case=False, na=False)].copy().reset_index(drop=True)
swDataFilter.tail(2)

,UploadKey,APINumber,JobEndDate,IngredientName,Purpose,TradeName,MassIngredient,PercentHFJob,IngredientKey,TotalBaseWaterVolume
25392,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - PREMIUM WHITE,7363600.0,13.596038,ad1a2155-6dfd-40a9-96e1-189eb344478e,5377176.0
25393,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - COMMON WHITE,1805900.0,3.334386,93c1b66d-f3f6-45a0-b17d-9aa939f357df,5377176.0

In [264]:
swDataFilter.tail(3)
#swDataFilter[swDataFilter['APINumber'] == '33105058870000']
#FracFocusRegistry[['UploadKey','APINumber','JobEndDate','IngredientName','Purpose','TradeName','MassIngredient','PercentHFJob','IngredientKey']][FracFocusRegistry['APINumber'] == '33105057810000'].head(60)

,UploadKey,APINumber,JobEndDate,IngredientName,Purpose,TradeName,MassIngredient,PercentHFJob,IngredientKey,TotalBaseWaterVolume
25391,92e2ee59-8ed0-4fca-8756-4ca2fda2bce3,33053060690000,2015-04-01,"Crystalline Silica, quartz",Sand - Bulk -North Dakota,Sand,0.0,9.011143,f405d911-1252-4e6f-aca3-fbfeb2ead66b,4238388.0
25392,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - PREMIUM WHITE,7363600.0,13.596038,ad1a2155-6dfd-40a9-96e1-189eb344478e,5377176.0
25393,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - COMMON WHITE,1805900.0,3.334386,93c1b66d-f3f6-45a0-b17d-9aa939f357df,5377176.0

In [265]:
#swDataFilter['derWeight'] = swDataFilter['TotalBaseWaterVolume']*9.62*swDataFilter['PercentHFJob']
swDataFilter['derWeight'] = swDataFilter['TotalBaseWaterVolume']*.0935*swDataFilter['PercentHFJob'] ## appears to give closest values to MassIngredient when both are given

In [266]:
#swDataFilter[(swDataFilter['derWeight'] >0)&(swDataFilter['MassIngredient'] == 0)]
swDataFilter.tail(6)

,UploadKey,APINumber,JobEndDate,IngredientName,Purpose,TradeName,MassIngredient,PercentHFJob,IngredientKey,TotalBaseWaterVolume,derWeight
25388,2888ef94-ca24-44e2-b316-d101730c9224,33105036010000,2015-03-31,Water,"Propping Agent, Gel Slurry, Crosslinker, Frict...","Sand (Proppant), DWP-151, DWP-126, DWP-621, DW...",46391.57,0.271840,6ce29dd9-b030-480a-b4b3-75ec61f7341b,1741437.0,4.426217e+04
25389,2888ef94-ca24-44e2-b316-d101730c9224,33105036010000,2015-03-31,Crystalline silica (Quartz),"Propping Agent, Gel Slurry, Crosslinker, Frict...","Sand (Proppant), DWP-151, DWP-126, DWP-621, DW...",2374676.07,13.914750,41fc62e6-e4b5-4023-ad8e-b5c3500b0bb2,1741437.0,2.265660e+06
25390,92e2ee59-8ed0-4fca-8756-4ca2fda2bce3,33053060690000,2015-04-01,"Crystalline Silica, quartz",Sand - Bulk -North Dakota,Sand,0.00,0.806457,ba86a925-62d0-4008-b41d-81746ddb541b,4238388.0,3.195903e+05
25391,92e2ee59-8ed0-4fca-8756-4ca2fda2bce3,33053060690000,2015-04-01,"Crystalline Silica, quartz",Sand - Bulk -North Dakota,Sand,0.00,9.011143,f405d911-1252-4e6f-aca3-fbfeb2ead66b,4238388.0,3.571019e+06
25392,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - PREMIUM WHITE,7363600.00,13.596038,ad1a2155-6dfd-40a9-96e1-189eb344478e,5377176.0,6.835625e+06
25393,8607b4f6-3380-42dd-8ec8-a396d01fd988,33053061280000,2015-04-02,"Crystalline silica, quartz",Proppant,SAND - COMMON WHITE,1805900.00,3.334386,93c1b66d-f3f6-45a0-b17d-9aa939f357df,5377176.0,1.676416e+06

In [267]:
#swDataFilter[(swDataFilter['derWeight'] >0)&(swDataFilter['MassIngredient'] == 0)]['derWeight'].mean()
swDataFilter[(swDataFilter['MassIngredient'] > 0)]['MassIngredient'].mean()

2705147.1124303653

In [268]:
def weightCondition(s):
    if (s['MassIngredient'] > 0):
        return s['MassIngredient']
    else:
        return s['derWeight']

In [269]:
swDataFilter['bestWeight'] = swDataFilter.apply(weightCondition, axis=1)

In [272]:
#SandUsed = swDataFilter[['UploadKey,'APINumber','JobEndDate','MassIngredient']].groupby(['UploadKey','APINumber','JobEndDate']).sum().rename(columns={'MassIngredient':'SandLB'}).reset_index()
SandUsed = swDataFilter[['UploadKey','APINumber','JobEndDate','bestWeight']].groupby(['UploadKey','APINumber','JobEndDate']).sum().rename(columns={'bestWeight':'SandLB'}).reset_index()

In [273]:
SandUsed = SandUsed[SandUsed['SandLB'] > 0]
SandUsed.reset_index(drop=True).tail(6)
#SandUsed[SandUsed['APINumber'] == '33105057410000']

,UploadKey,APINumber,JobEndDate,SandLB
7750,ffe33196-271a-4c31-affb-c5cce0aafbd7,33105034080000,2014-10-23,5.070197e+06
7751,ffeb8d65-66a6-47e5-835e-b002806305bc,33053091850000,2023-01-12,4.738717e+06
7752,ffef3fcc-9185-41d6-85e0-ea992071237f,33053084960000,2018-08-22,7.154146e+06
7753,fff39d2a-da18-432b-899f-012837eef9b6,33053091710000,2020-08-23,1.304442e+07
7754,fff9db51-a9e1-4698-b29d-9ff597aae7fd,33025036880000,2021-04-05,7.992000e+06
7755,fffb8798-b804-447b-856f-cde632d7bb7d,33061038180000,2017-04-30,1.367250e+07

In [287]:
ffWellsND = ffWellsND.merge(SandUsed[['UploadKey','SandLB']], how='left', left_on = 'pKey', right_on = 'UploadKey' )

In [289]:
ffWellsND.drop(['pKey','UploadKey'], axis=1, inplace=True)

In [290]:
ffWellsND.tail()

            APINumber  JobEndDate  TotalBaseWaterVolume      SandLB
16088  33025041590000  2023-08-12             5686172.0  8841309.84
16089  33025034420000  2023-08-12             5680525.0  6012038.00
16090  33025034470000  2023-08-13             6166909.0  6541850.00
16091  33025046910000  2023-08-13             7494120.0  8521120.00
16092  33025046920000  2023-08-13             7266037.0  8522543.00